name: voicevox_flutter_example
description: Demonstrates how to use the voicevox_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  voicevox_flutter:
    path: ../

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  audioplayers: ^3.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/open_jtalk_dic_utf_8-1.11/
  - assets/model/